# Generated by Django 4.2.2 on 2023-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='datenaissance_client',
            field=models.DateField(null=True),
        ),
    ]
