# Generated by Django 4.2.2 on 2023-06-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0003_produit_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monsite.livraison'),
        ),
    ]
