# Generated by Django 4.2.2 on 2023-07-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0005_panier_remove_produit_commande_commande_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='qte_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
